name: test1

on:
  push:
    branches:
      - main

jobs:
  hello:
    runs-on: [ubuntu-latest, windows-latest]
    steps:
      - name: yolo
        run: echo "hi hi!"
  # build:
  #   runs-on: [ubuntu-latest, windows-latest]