name: CICD

on:
  push:
    branches:
      - main
    tags:
      - "v*"

jobs:
  hello:
    runs-on: windows-latest
    steps:
      - name: yolo
        run: echo "hi hi!"
  create_release:
    if: startsWith(github.ref, 'refs/tags/v')
    name: Create Release
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: Create Release-step
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}

  build:
    needs: create_release
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: hiworld
            asset_name: hiworld-${{ github.ref }}-linux-amd64
          - os: macos-latest
            artifact_name: hiworld
            asset_name: hiworld-${{ github.ref }}-macos-amd64
          - os: windows-latest
            artifact_name: hiworld
            asset_name: hiworld-${{ github.ref }}-windows.exe

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.19.x'
      - name: build
        run:
          go build
      - name: run
        run:
          echo {{ matrix.artifact_name }}
      - name: upload assets
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create_release.outputs.upload_url }}
          asset_name: ${{ matrix.asset_name }}
          asset_path: ${{ matrix.artifact_name }}
          asset_content_type: application/octet-stream
      # - name: upload windows
      #   if: matrix.platform == 'windows-latest'
      #   uses: actions/upload-release-asset@v1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     upload_url: ${{ needs.create_release.outputs.upload_url }}
      #     asset_name: hiworld-${{ matrix.platform }}-${{ github.ref }}.exe
      #     asset_path: ./hiworld
      #     asset_content_type: application/octet-stream