name: test1

on:
  push:
    branches:
      - main

jobs:
  hello:
    runs-on: windows-latest
    steps:
      - name: yolo
        run: echo "hi hi!"
  build:
    strategy:
      matrix:
        platform: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
      - name: go version
        run:
          go version
