name: test1

on:
  push:
    branches:
      - main

jobs:
  hello:
    strategy:
      matrix:
        platform: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: yolo
        run: echo "hi hi!"
  # build:
  #   runs-on: [ubuntu-latest, windows-latest]